# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 6) do

  create_table "companies", :force => true do |t|
    t.column "name",                         :string,                                :default => "", :null => false
    t.column "last_FY_net_profit",           :decimal, :precision => 8, :scale => 2
    t.column "previous_quarter_net_profit",  :decimal, :precision => 8, :scale => 2
    t.column "latest_quarter_net_profit",    :decimal, :precision => 8, :scale => 2
    t.column "eps",                          :decimal, :precision => 8, :scale => 2
    t.column "pe_ratio",                     :decimal, :precision => 8, :scale => 2
    t.column "book_value",                   :decimal, :precision => 8, :scale => 2
    t.column "ronw",                         :decimal, :precision => 8, :scale => 2
    t.column "market_cap",                   :decimal, :precision => 8, :scale => 2
    t.column "dividend_per_share",           :decimal, :precision => 8, :scale => 2
    t.column "year_high",                    :decimal, :precision => 8, :scale => 2
    t.column "year_low",                     :decimal, :precision => 8, :scale => 2
    t.column "latest_price",                 :decimal, :precision => 8, :scale => 2,                 :null => false
    t.column "price_to_book_value_multiple", :decimal, :precision => 8, :scale => 2
    t.column "rating",                       :string
    t.column "sector_id",                    :integer,                                               :null => false
  end

  create_table "sectors", :force => true do |t|
    t.column "name",                         :string,                                :default => "", :null => false
    t.column "outlook",                      :string
    t.column "child_url",                    :string
    t.column "eps",                          :decimal, :precision => 8, :scale => 2
    t.column "pe_ratio",                     :decimal, :precision => 8, :scale => 2
    t.column "ronw",                         :decimal, :precision => 8, :scale => 2
    t.column "price_to_book_value_multiple", :decimal, :precision => 8, :scale => 2
  end

end
